### ISSUE TITLE
Suggestion: build_demo_qt/glfw switches

### ISSUE THREAD

**Issue by GPMueller** [FlorianRhiem/VFRendering#1]
Two switches which could be passed to the project would make sense in order to (optionally) reduce dependencies.

**Comment by FlorianRhiem** [comment]
The qt demo will stay independent, as it is meant to be built with qmake.
I have removed the demo using GLFW from the default targets of the Makefile and added and option BUILD_DEMO to the CMake build to disable building the demo by default.
