### ISSUE TITLE
Demo does not compile

### ISSUE THREAD

**Issue by MRedies** [FlorianRhiem/VFRendering#6]
It seems the demo does not compile: 
```
/usr/bin/ld: libVFRendering.a(glad.c.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
/usr/lib/libdl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/VFRenderingDemo.dir/build.make:99: VFRenderingDemo] Error 1
make[1]: *** [CMakeFiles/Makefile2:143: CMakeFiles/VFRenderingDemo.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```
I believe this is because the -ldl is missing in the linking. If I append this manually to the linkline:

`/usr/bin/c++     CMakeFiles/VFRenderingDemo.dir/demo.cxx.o  -o VFRenderingDemo libVFRendering.a /usr/lib/libglfw.so.3.2 qhull-prefix/src/qhull-build/libqhullcpp.a qhull-prefix/src/qhull-build/libqhullstatic_r.a -ldl`

it works.

**Comment by GPMueller** [comment]
Something like
```cmake
### OSX and Unix need libdl
if( APPLE )
    target_link_libraries( ${PROJECT_NAME}Demo dl )
elseif( UNIX )
    target_link_libraries( ${PROJECT_NAME}Demo dl )
elseif( WIN32 )
endif()
```
in the main `CMakeLists.txt` should resolve this.

**Comment by FlorianRhiem** [comment]
I added GitLab CI builds that build the demo and 0f4835be8396734113a94716e7b85da31883747a should fix this issue.
